basePath: /accounts
consumes:
    - application/json
definitions:
    ExchangeModel:
        description: An ExchangeModel is gives information about the connected exchanges
        properties:
            connected:
                example: true
                type: boolean
                x-go-name: Connected
            id:
                example: 23
                format: int64
                type: integer
                x-go-name: Id
            image_src:
                example: bybit
                type: string
                x-go-name: ImageSrc
            is_active:
                example: true
                type: boolean
                x-go-name: IsActive
            name:
                example: bybit
                type: string
                x-go-name: Name
            short:
                example: bybit
                type: string
                x-go-name: Short
        type: object
        x-go-package: github.com/kryptomind/bidboxapi/AccountsService/api/controllers
    ExchangeRes:
        properties:
            body:
                $ref: '#/definitions/ExchangeModel'
        required:
            - body
        type: object
        x-go-package: github.com/kryptomind/bidboxapi/AccountsService/api/controllers
    Key:
        properties:
            api_key:
                description: Api Key
                example: 829sksh8jws9020wp
                type: string
                x-go-name: ApiKey
            compound:
                description: Auto Compound
                example: true
                type: boolean
                x-go-name: Compound
            key_id:
                description: ID of Key
                example: 9283939ede-829kskiisii2-kdeoidekeo2-ieodke9ese
                format: uuid
                type: string
                x-go-name: Keyid
            mode:
                description: Mode
                example: conservative
                type: string
                x-go-name: Mode
            passphrase:
                description: Passphrase
                example: thisisapassphrase
                type: string
                x-go-name: Passphrase
            secret:
                description: Secret Key
                example: 7276shsjj299skwks93ls
                type: string
                x-go-name: SecretKey
            service:
                description: Exchange of key
                example: bitget
                type: string
                x-go-name: Service
            start:
                description: Enable Key
                example: true
                type: boolean
                x-go-name: Start
            strategy:
                description: Strategy
                example: cycle
                type: string
                x-go-name: Strategy
            trade_amount:
                description: Trade Amount
                example: 200
                format: int64
                type: integer
                x-go-name: TradeAmount
            user_email:
                description: User Email
                example: abc@gmail.com
                type: string
                x-go-name: UserEmail
        type: object
        x-go-package: github.com/kryptomind/bidboxapi/AccountsService/api/models
info:
    description: Documentation for BidBox Accounts API
    version: 1.0.0
paths:
    /connected:
        get:
            consumes:
                - application/json
            description: |-
                This will show all available pets by default.
                You can get the pets that are out of stock
            operationId: listPets
            parameters:
                - description: user email
                  in: query
                  name: email
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: ExchangeRes
                    schema:
                        $ref: '#/definitions/ExchangeRes'
                "404":
                    $ref: '#/responses/connected'
                    description: account not found
                default:
                    $ref: '#/responses/genericError'
            schemes:
                - http
                - https
            summary: Get Connected exchanges for a user.
            tags:
                - pets
                - users
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
